logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "both"                                                   # 'both', 'apk' or 'module'
excluded-patches = "always-autorepeat comments copy-video-url custom-video-buffer disable-auto-captions disable-fullscreen-panels disable-player-popup-panels disable-shorts-on-startup disable-zoom-haptics enable-debugging external-downloads hdr-auto-brightness navigation-buttons open-links-externally seekbar-tapping spoof-app-version swipe-controls tablet-mini-player video-speed wide-searchbar"                                                 # space-seperated patches to exclude (multiline strings are not supported)
included-patches = "client-spoof custom-branding hide-ads hide-cast-button hide-watermark minimized-playback old-quality-layout premium-heading remember-video-quality return-youtube-dislike sponsorblock theme vanced-microg-support video-ads"                                                 # space-seperated patches to include (non-excluded patches are included by default)
version = "latest"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
exclusive-patches = false                                             # excludes all patches by default and only applies included-patches
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"
